POST http://127.0.0.1:8000/auth/signup
Content-Type: application/json

{
    "username": "rayane",
    "password": "123456789",
    "first_name": "saliha",
    "last_name": "bailly",
    "role": "Paatient"
}


###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{ "username": "drbailyy", "password": "pass123" }

###

GET http://127.0.0.1:8000/auth/test 
Content-Type: application/json
Authorization: Bearer 5c2d53de19e64ea7c4e940fb8c4d04eb120e66d2
###

POST http://127.0.0.1:8000/creerdpi
Content-Type: application/json

{
    "data": {
    "nom": "malak",
    "prenom": "hhhh",
    "date_naissance": "1998-12-12",
    "telephone": "0607080910",
    "adr": "12 rue de la paix",
    "nss": "12345678800",
    "mutuelle": "jsp wsh m3ntha",
    "nom_personne": "Bailly",
    "prenom_personne": "Thomas",
    "telephone_personne": "0607080910"
}
}
###

GET http://127.0.0.1:8000/patients
Content-Type: application/json


###
GET http://127.0.0.1:8000/dpi/patients/nss/123456789
Content-Type: application/json

###
GET http://localhost:8000/ordonnance/1
Content-Type: application/json
###

POST http://127.0.0.1:8000/ordonnances/1/valider
Content-Type: application/json
{
  "validation": true
}

###
POST http://127.0.0.1:8000/distributions
Content-Type: application/json

{
  "ordonnance_id": 1,
  "traitement_id": 1,
  "quantite": 2
}