# Generated by Django 5.1.4 on 2024-12-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpi',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
