# Generated by Django 5.1.4 on 2025-01-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
