# Generated by Django 5.1.4 on 2025-01-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilanradiologique',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='radiologie/'),
        ),
    ]
