# Generated by Django 5.1.4 on 2025-01-03 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='etablissement',
        ),
        migrations.AddField(
            model_name='consultation',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='med.medecin'),
        ),
        migrations.DeleteModel(
            name='Etablissement',
        ),
    ]
