# Generated by Django 5.1.4 on 2024-12-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_remove_dpi_utilisateur_delete_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpi',
            name='antecedents_medicaux',
            field=models.TextField(default='Aucun antecedent', help_text='Antecedents medicaux du patient'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
