# Generated by Django 5.1.4 on 2025-01-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_alter_bilanradiologique_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilanradiologique',
            old_name='image_url',
            new_name='image',
        ),
    ]
