# Generated by Django 5.1.4 on 2024-12-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonneAContacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('consommation', models.CharField(help_text="Par exemple : '3 comprimés'", max_length=100)),
                ('frequence', models.IntegerField(help_text='Par exemple : tous les 3 jours', verbose_name='Fréquence (en jours)')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField(verbose_name='Date de naissance')),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=15)),
                ('nss', models.CharField(max_length=15, unique=True)),
                ('mutuelle', models.CharField(blank=True, max_length=100, null=True)),
                ('medecins', models.ManyToManyField(blank=True, related_name='patients', to='dpi.medecin')),
                ('personne_a_contacter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='dpi.personneacontacter')),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedants_medicaux', models.TextField(default='Aucun antecedant', help_text='Antecedants medicaux du patient')),
                ('patient', models.OneToOneField(help_text='Le patient associé à ce DSI', on_delete=django.db.models.deletion.CASCADE, related_name='dossier_patient', to='dpi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validee', models.BooleanField(default=False)),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('dpi', models.ForeignKey(help_text='DPI associé à cette ordonnance', on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='dpi.dpi')),
                ('traitements', models.ManyToManyField(help_text='Liste des traitements inclus dans cette ordonnance', related_name='ordonnances', to='dpi.traitement')),
            ],
        ),
    ]
